version: '2'
services:
  repo:
    image: docker-internal.alfresco.com/platform:5.2.1-SNAPSHOT
    environment:
         JAVA_OPTS : "-Dsolr.host=solr6  -Dsolr.port=8983 -Dsolr.secureComms=none
         -Dsolr.base.url=/solr -Dindex.subsystem.name=solr6"
    ports:
          - "7203:7203" #JMX connect via service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
          - "5005:5005" #Java debugging
          - "8082:8080" #Browser port
  solr6:
    image: docker-internal.alfresco.com/search-services:1.0.0
    environment:
      #Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: repo
      SOLR_ALFRESCO_PORT: 8080
      #Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: 8983

      #Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS : alfresco,archive
    depends_on:
          - repo
    ports:
      - "8083:8983" #Browser port